name: catsvsdogs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cycler=0.10.0
  - dbus=1.13.16
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.1
  - jpeg=9b
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - nodejs=10.13.0
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - qt=5.9.7
  - readline=8.0
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - absl-py==0.9.0
      - astunparse==1.6.3
      - cachetools==4.1.1
      - chardet==3.0.4
      - gast==0.3.3
      - google-auth==1.20.1
      - google-auth-oauthlib==0.4.1
      - google-pasta==0.2.0
      - grpcio==1.31.0
      - h5py==2.10.0
      - idna==2.10
      - kaggle==1.5.6
      - keras-preprocessing==1.1.2
      - markdown==3.2.2
      - numpy==1.18.5
      - oauthlib==3.1.0
      - opt-einsum==3.3.0
      - prompt-toolkit==1.0.14
      - protobuf==3.13.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.6.1
      - pyinquirer==1.0.3
      - python-slugify==4.0.1
      - regex==2020.7.14
      - requests==2.24.0
      - requests-oauthlib==1.3.0
      - rsa==4.6
      - scipy==1.4.1
      - tensorboard==2.3.0
      - tensorboard-plugin-wit==1.7.0
      - tensorflow==2.3.0
      - tensorflow-cpu==2.3.0
      - tensorflow-estimator==2.3.0
      - tensorflow-hub==0.7.0
      - tensorflowjs==2.3.0
      - termcolor==1.1.0
      - text-unidecode==1.3
      - tqdm==4.48.2
      - urllib3==1.24.3
      - wcwidth==0.2.5
      - werkzeug==1.0.1
      - wrapt==1.12.1
