name: catsvsdogs
channels:
  - defaults
dependencies:
  - matplotlib=3.2.2
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.8.5
  - pip:
      - kaggle==1.5.6
      - tensorflow==2.3.0
      - tensorflowjs==2.3.0
